library(plm)
library(tidyverse)
IDEMIA<-read_csv("~/R/PROYECTO.csv")
attach(PROYECTO)
y<-cbind(Hom)
x<-cbind(Sec,RcV,PIBCAP,HabKm2,IED,VioSex,PIBUSD,Pob,Exto,PEA,Deuda)
pooling<-plm(y~x, data=PROYECTO,model = "pooling", index=c("Entidad", "Year"))
summary(pooling)
fixed<-plm(y~x,data = PROYECTO,index = c("Entidad", "Year"),model = "within")
summary(fixed)
random<-plm(y~x,data = PROYECTO, index = c("Entidad", "Year"),model = "random")
summary(random)
